project:
  type: website
  output-dir: docs

website:
  title: "Urban Research Station<br><span style='font-size: x-small;'>at the Natural History Museum</span>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - case-studies.qmd
      - text: Publications
        menu:
          - href: publications.qmd
            text: Articles
          - implementation-reports.qmd
      - team.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



