project:
  type: website
  output-dir: docs
  pre-render:
    - python ./scripts/generate_trees_from_csv.py
    - python ./scripts/generate_trees_from_epicollect.py --force
    - python ./scripts/generate_tree_list.py
    - python ./scripts/generate_recent_trees.py
    - python ./scripts/generate_articles_from_bib.py
    - python ./scripts/generate_reports_index.py
    - python ./scripts/render_articles_to_pdf.py --output-dir docs/assets/pdfs
    - python ./scripts/clean_pdfs.py --pattern "docs/assets/pdfs/*.pdf" --inplace --no-backup
website:
  title: "Living<br>Labs"
  navbar:
    logo: assets/images/nhm_logo_white.png
    left:
      - href: index.qmd
        text: Home
      - text: Living Labs
        menu:
          - href: living-labs/urban-research-station.qmd
            text: Urban Research Station
          - href: living-labs/tring.qmd
            text: Tring Living Lab
      - text: Environments
        menu:
          - href: environments/soil.qmd
            text: Soil
          - href: environments/freshwater.qmd
            text: Freshwater
      - text: Studies
        menu:
          - href: case-studies.qmd
          - href: student-projects.qmd
      - text: Trees
        menu:
            - href: trees/index.qmd
            - href: trees/family/index.qmd
            - href: trees/genus/index2.qmd
            - href: trees/genus/index.qmd
      - text: Publications
        menu:
          - href: articles.qmd
            text: Articles
          - href: reports.qmd
            text: NHM Living Labs Reports
      - team.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
