project:
  type: website
  output-dir: docs

website:
  title: "Urban Research Station"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - case-studies.qmd
      - publications.qmd
      - team.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



